services:
  webmvc:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=community_safety_db;User=dev;Password=123456;
    depends_on:
      - db
  
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: community_safety_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local    
      